name: SimpleSetLobby
main: Luthfi\SimpleSetLobby\Main
version: 1.0.0
api: 5.0.0
author: Luthfi
commands:
  setlobby:
    description: Set the lobby location
    usage: /setlobby
    permission: setlobby.command
  lobbyui:
    description: LobbyUI
    usage: /lobbyui
    permission: lobbyui.command
permissions:
  setlobby.cmd:
    description: Allows the user to set the lobby
    default: op
  lobbyui.cmd:
    description: Allows the user to open the lobby UI
    default: op
  setlobby.ui:
    description: Allows player to set lobby location
    default: op
  unsetlobby.ui:
    description: Allows player to unset lobby location
