name: SimpleSetLobby
main: Luthfi\SimpleSetLobby\Main
version: 2.0.0
api: 5.0.0
author: YourName
commands:
  setlobby:
    description: Set the lobby location
    usage: /setlobby
    permission: setlobby.command
  lobbyui:
    description: LobbyUI
    usage: /lobbyui
    permission: lobbyui.command
permissions:
  setlobby.cmd:
    description: Allows the user to set the lobby
    default: op
  lobbyui.cmd:
    description: Allows the user to open the lobby UI
    default: op
